var data=
[
    {
        "date":"2018年5月1日",
        "project":"XXXX项目",
        "company":"XXXX公司",
        "process":["1","1","0","0"],
    },{
        "date":"2018年5月2日",
        "project":"XXXX项目",
        "company":"XXXX公司",
        "process":[1,1,1,1]
    },{
        "date":"2018年5月3日",
        "project":"XXXX项目",
        "company":"XXXX公司",
        "process":[1,1,0,1]
    },{
        "date":"2018年5月4日",
        "project":"XXXX项目",
        "company":"XXXX公司",
        "process":[1,0,0,0]
    },{
        "date":"2018年5月5日",
        "project":"XXXX项目",
        "company":"XXXX公司",
        "process":[1,0,0,0]
    },{
        "date":"2018年5月6日",
        "project":"XXXX项目",
        "company":"XXXX公司",
        "process":[1,0,0,0]
    },{
        "date":"2018年5月7日",
        "project":"XXXX项目",
        "company":"XXXX公司",
        "process":[0,0,0,0]
    },{
        "date":"2018年5月8日",
        "project":"XXXX项目",
        "company":"XXXX公司",
        "process":[0,1,0,0]
    },{
        "date":"2018年5月9日",
        "project":"XXXX项目",
        "company":"XXXX公司",
        "process":[0,1,0,0]
    },{
        "date":"2018年5月10日",
        "project":"XXXX项目",
        "company":"XXXX公司",
        "process":[1,1,0,1]
    },    {
        "date":"2018年6月1日",
        "project":"XXXX项目",
        "company":"XXXX公司",
        "process":[1,1,0,0]
    },
    {
        "date":"2018年6月2日",
        "project":"XXXX项目",
        "company":"XXXX公司",
        "process":[1,1,1,1]
    },
    {
        "date":"2018年6月3日",
        "project":"XXXX项目",
        "company":"XXXX公司",
        "process":[1,1,0,1]
    },
    {
        "date":"2018年6月4日",
        "project":"XXXX项目",
        "company":"XXXX公司",
        "process":[1,0,0,0]
    },{
        "date":"2018年6月5日",
        "project":"XXXX项目",
        "company":"XXXX公司",
        "process":[1,0,0,0]
    },{
        "date":"2018年6月6日",
        "project":"XXXX项目",
        "company":"XXXX公司",
        "process":[1,0,0,0]
    },{
        "date":"2018年6月7日",
        "project":"XXXX项目",
        "company":"XXXX公司",
        "process":[0,0,0,0]
    },{
        "date":"2018年6月8日",
        "project":"XXXX项目",
        "company":"XXXX公司",
        "process":[0,1,0,0]
    },{
        "date":"2018年6月9日",
        "project":"XXXX项目",
        "company":"XXXX公司",
        "process":[0,1,0,0]
    },{
        "date":"2018年6月10日",
        "project":"XXXX项目",
        "company":"XXXX公司",
        "process":[1,1,0,1]
    },
    {
        "date":"2018年7月1日",
        "project":"XXXX项目",
        "company":"XXXX公司",
        "process":[1,1,0,0]
    },
    {
        "date":"2018年7月2日",
        "project":"XXXX项目",
        "company":"XXXX公司",
        "process":[1,1,1,1]
    },
    {
        "date":"2018年7月3日",
        "project":"XXXX项目",
        "company":"XXXX公司",
        "process":[1,1,0,1]
    },
    {
        "date":"2018年7月4日",
        "project":"XXXX项目",
        "company":"XXXX公司",
        "process":[1,0,0,0]
    },{
        "date":"2018年7月5日",
        "project":"XXXX项目",
        "company":"XXXX公司",
        "process":[1,0,0,0]
    },{
        "date":"2018年7月6日",
        "project":"XXXX项目",
        "company":"XXXX公司",
        "process":[1,0,0,0]
    },{
        "date":"2018年7月7日",
        "project":"XXXX项目",
        "company":"XXXX公司",
        "process":[0,0,0,0]
    },{
        "date":"2018年7月8日",
        "project":"XXXX项目",
        "company":"XXXX公司",
        "process":[0,1,0,0]
    },{
        "date":"2018年7月9日",
        "project":"XXXX项目",
        "company":"XXXX公司",
        "process":[0,1,0,0]
    },{
        "date":"2018年7月10日",
        "project":"XXXX项目",
        "company":"XXXX公司",
        "process":[1,1,0,1]
    },
    {
        "date":"2018年8月1日",
        "project":"XXXX项目",
        "company":"XXXX公司",
        "process":[1,1,0,0]
    },
    {
        "date":"2018年8月2日",
        "project":"XXXX项目",
        "company":"XXXX公司",
        "process":[1,1,1,1]
    },
    {
        "date":"2018年8月3日",
        "project":"XXXX项目",
        "company":"XXXX公司",
        "process":[1,1,0,1]
    },
    {
        "date":"2018年8月4日",
        "project":"XXXX项目",
        "company":"XXXX公司",
        "process":[1,0,0,0]
    },{
        "date":"2018年8月5日",
        "project":"XXXX项目",
        "company":"XXXX公司",
        "process":[1,0,0,0]
    },{
        "date":"2018年8月6日",
        "project":"XXXX项目",
        "company":"XXXX公司",
        "process":[1,0,0,0]
    },{
        "date":"2018年8月7日",
        "project":"XXXX项目",
        "company":"XXXX公司",
        "process":[0,0,0,0]
    },{
        "date":"2018年8月8日",
        "project":"XXXX项目",
        "company":"XXXX公司",
        "process":[0,1,0,0]
    },{
        "date":"2018年8月9日",
        "project":"XXXX项目",
        "company":"XXXX公司",
        "process":[0,1,0,0]
    },{
        "date":"2018年8月10日",
        "project":"XXXX项目",
        "company":"XXXX公司",
        "process":[1,1,0,1]
    },
    {
        "date":"2018年9月1日",
        "project":"XXXX项目",
        "company":"XXXX公司",
        "process":[1,1,0,0]
    },
    {
        "date":"2018年9月2日",
        "project":"XXXX项目",
        "company":"XXXX公司",
        "process":[1,1,1,1]
    },
    {
        "date":"2018年9月3日",
        "project":"XXXX项目",
        "company":"XXXX公司",
        "process":[1,1,0,1]
    },
    {
        "date":"2018年9月4日",
        "project":"XXXX项目",
        "company":"XXXX公司",
        "process":[1,0,0,0]
    },{
        "date":"2018年9月5日",
        "project":"XXXX项目",
        "company":"XXXX公司",
        "process":[1,0,0,0]
    },{
        "date":"2018年9月6日",
        "project":"XXXX项目",
        "company":"XXXX公司",
        "process":[1,0,0,0]
    },{
        "date":"2018年9月7日",
        "project":"XXXX项目",
        "company":"XXXX公司",
        "process":[0,0,0,0]
    },{
        "date":"2018年9月8日",
        "project":"XXXX项目",
        "company":"XXXX公司",
        "process":[0,1,0,0]
    },{
        "date":"2018年9月9日",
        "project":"XXXX项目",
        "company":"XXXX公司",
        "process":[0,1,0,0]
    },{
        "date":"2018年9月10日",
        "project":"XXXX项目",
        "company":"XXXX公司",
        "process":[1,1,0,1]
    }
]